services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - CGO_ENABLED=0
    labels:
      - "env=dev"
      - "role=devcontainer"
